# Generated by Django 5.2.15 on 2026-06-28 18:46

import aplicaciones.auditoria.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_original', models.CharField(max_length=300)),
                ('nombre_fisico', models.CharField(max_length=300)),
                ('extension', models.CharField(max_length=20)),
                ('mime_type', models.CharField(max_length=150)),
                ('tamano_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('firma', 'Firma'), ('multimedia', 'Multimedia'), ('archivo_general', 'Archivo general')], max_length=30)),
                ('ruta_relativa', models.CharField(max_length=500)),
                ('url_publica', models.CharField(blank=True, max_length=500)),
                ('es_publico', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('formulario', 'Formulario'), ('pregunta', 'Pregunta'), ('respuesta', 'Respuesta'), ('internacionalizacion', 'Internacionalizacion'), ('configuracion', 'Configuracion'), ('catalogo', 'Catalogo'), ('notificacion', 'Notificacion'), ('otro', 'Otro')], max_length=30)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado'), ('cuarentena', 'Cuarentena'), ('procesando', 'Procesando')], default='activo', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('usuario_keycloak', models.CharField(blank=True, max_length=255)),
                ('uuid_sesion', models.UUIDField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de repositorio',
                'verbose_name_plural': 'Archivos de repositorio',
                'ordering': ['-fecha_carga'],
                'indexes': [models.Index(fields=['uuid'], name='archivos_ar_uuid_6cc166_idx'), models.Index(fields=['tipo_archivo'], name='archivos_ar_tipo_ar_4640ec_idx'), models.Index(fields=['estado'], name='archivos_ar_estado_d74829_idx'), models.Index(fields=['origen'], name='archivos_ar_origen_62694c_idx'), models.Index(fields=['checksum_sha256'], name='archivos_ar_checksu_ccb13b_idx'), models.Index(fields=['fecha_carga'], name='archivos_ar_fecha_c_a26944_idx')],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
    ]
