# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivorepositorio',
            name='origen',
            field=models.CharField(choices=[('formulario', 'Formulario'), ('pregunta', 'Pregunta'), ('respuesta', 'Respuesta'), ('internacionalizacion', 'Internacionalización'), ('configuracion', 'Configuración'), ('catalogo', 'Catálogo'), ('notificacion', 'Notificación'), ('otro', 'Otro')], max_length=30),
        ),
    ]
