# Generated by Django 5.2.15 on 2026-06-28 19:16

import aplicaciones.auditoria.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('respuestas', 'Respuestas'), ('catalogos', 'Catalogos'), ('analitica', 'Analitica')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('finalizada', 'Finalizada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('usuario', models.CharField(blank=True, max_length=255)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('formato', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON'), ('sql', 'SQL'), ('pdf', 'PDF'), ('ods', 'ODS')], max_length=10)),
                ('parametros', models.JSONField(blank=True, default=dict, null=True)),
                ('registros_exportados', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportaciones', to='archivos.archivorepositorio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportacion',
                'verbose_name_plural': 'Exportaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['uuid'], name='exportacion_uuid_69c769_idx'), models.Index(fields=['tipo'], name='exportacion_tipo_a2fdf1_idx'), models.Index(fields=['estado'], name='exportacion_estado_c6ddc7_idx'), models.Index(fields=['formato'], name='exportacion_formato_1e3779_idx')],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
    ]
