# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='tipo',
            field=models.CharField(choices=[('respuestas', 'Respuestas'), ('catalogos', 'Catálogos'), ('analitica', 'Analítica')], max_length=30),
        ),
    ]
