# Generated by Django 5.2.15 on 2026-06-28 16:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAnonima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_sesion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('idioma', models.CharField(blank=True, max_length=20)),
                ('zona_horaria', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('abandonada', 'Abandonada'), ('sincronizada', 'Sincronizada')], default='iniciada', max_length=20)),
                ('token_cliente', models.CharField(blank=True, max_length=255)),
                ('es_offline', models.BooleanField(default=False)),
                ('fecha_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_anonimas', to='formularios.formulario')),
                ('version_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_anonimas', to='formularios.formularioversion')),
            ],
            options={
                'verbose_name': 'Sesion anonima',
                'verbose_name_plural': 'Sesiones anonimas',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['uuid_sesion'], name='sesiones_an_uuid_se_8c8060_idx'), models.Index(fields=['estado'], name='sesiones_an_estado_3dd428_idx'), models.Index(fields=['formulario'], name='sesiones_an_formula_e8006d_idx'), models.Index(fields=['version_formulario'], name='sesiones_an_version_e03f03_idx')],
            },
        ),
    ]
