# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones_anonimas', '0004_sesionanonima_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesionanonima',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Sesión anónima', 'verbose_name_plural': 'Sesiones anónimas'},
        ),
    ]
