# Generated by Django 5.2.15 on 2026-06-28 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respuestas', '0005_respuesta_dispositivo_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictoSincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid_local', models.UUIDField(db_index=True)),
                ('tipo_conflicto', models.CharField(choices=[('version', 'Version'), ('duplicado', 'Duplicado'), ('eliminado', 'Eliminado'), ('modificacion', 'Modificacion'), ('otro', 'Otro')], db_index=True, max_length=20)),
                ('valor_cliente', models.JSONField(blank=True, null=True)),
                ('valor_servidor', models.JSONField(blank=True, null=True)),
                ('resolucion', models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('servidor', 'Servidor'), ('manual', 'Manual')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflictos_sincronizacion', to='respuestas.respuesta')),
            ],
            options={
                'verbose_name': 'Conflicto de sincronizacion',
                'verbose_name_plural': 'Conflictos de sincronizacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OperacionSincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid_local', models.UUIDField(db_index=True)),
                ('uuid_sesion', models.UUIDField(db_index=True)),
                ('dispositivo', models.CharField(max_length=150)),
                ('version_cliente', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('sincronizada', 'Sincronizada'), ('conflicto', 'Conflicto'), ('error', 'Error'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_cliente', models.DateTimeField()),
                ('fecha_servidor', models.DateTimeField(auto_now_add=True)),
                ('numero_reintentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('origen', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('resultado', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Operacion de sincronizacion',
                'verbose_name_plural': 'Operaciones de sincronizacion',
                'ordering': ['-fecha_servidor'],
                'indexes': [models.Index(fields=['dispositivo'], name='sincronizac_disposi_e58f23_idx'), models.Index(fields=['fecha_servidor'], name='sincronizac_fecha_s_645862_idx'), models.Index(fields=['uuid_sesion', 'uuid_local'], name='sincronizac_uuid_se_c042d0_idx')],
            },
        ),
    ]
