# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conflictosincronizacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Conflicto de sincronización', 'verbose_name_plural': 'Conflictos de sincronizacion'},
        ),
        migrations.AlterModelOptions(
            name='operacionsincronizacion',
            options={'ordering': ['-fecha_servidor'], 'verbose_name': 'Operación de sincronización', 'verbose_name_plural': 'Operaciones de sincronizacion'},
        ),
    ]
