# Generated by Django 5.2.15 on 2026-06-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_hora', models.TimeField(blank=True, null=True)),
                ('valor_fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('valor_json', models.JSONField(blank=True, null=True)),
                ('archivo_nombre', models.CharField(blank=True, max_length=300)),
                ('archivo_ruta', models.CharField(blank=True, max_length=500)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('precision_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('origen_respuesta', models.CharField(choices=[('web', 'Web'), ('offline', 'Offline'), ('sincronizacion', 'Sincronizacion')], default='web', max_length=20)),
                ('fecha_respuesta_cliente', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta_servidor', models.DateTimeField(auto_now=True)),
                ('version_respuesta', models.PositiveIntegerField(default=1)),
                ('requiere_sincronizacion', models.BooleanField(default=False)),
                ('eliminada_logicamente', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='formularios.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['sesion', 'pregunta'],
            },
        ),
    ]
