# Generated by Django 5.2.15 on 2026-06-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respuestas', '0001_initial'),
        ('sesiones_anonimas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sesiones_anonimas.sesionanonima'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['sesion'], name='respuestas__sesion__cc7f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['pregunta'], name='respuestas__pregunt_8dbbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['origen_respuesta'], name='respuestas__origen__ea5d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['requiere_sincronizacion'], name='respuestas__requier_8716bb_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['eliminada_logicamente'], name='respuestas__elimina_aa5a80_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['fecha_respuesta_servidor'], name='respuestas__fecha_r_bc1e10_idx'),
        ),
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('sesion', 'pregunta'), name='uq_respuesta_sesion_pregunta'),
        ),
    ]
