# Generated by Django 5.2.15 on 2026-06-28 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_formulario_imagen_portada_repositorio'),
        ('respuestas', '0004_remove_respuesta_respuestas_esta_elim_idx_and_more'),
        ('sesiones_anonimas', '0003_remove_sesionanonima_sesiones_an_esta_elim_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='dispositivo_origen',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fecha_modificacion_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='uuid_local',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='version_cliente',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['uuid_local'], name='respuestas__uuid_lo_5072d5_idx'),
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['version_cliente'], name='respuestas__version_5bb7ce_idx'),
        ),
    ]
