# Generated by Django 5.2.15 on 2026-06-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='auditoria_r_entidad_0cbcba_idx',
            old_name='auditoria_entidad_entidad_id_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='auditoria_r_accion_dae68a_idx',
            old_name='auditoria_accion_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='auditoria_r_usuario_5ab20b_idx',
            old_name='auditoria_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='auditoria_r_identif_885d7e_idx',
            old_name='auditoria_keycloak_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='auditoria_r_uuid_se_b64bae_idx',
            old_name='auditoria_uuid_sesion_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='auditoria_r_fecha_a_82c07a_idx',
            old_name='auditoria_fecha_accion_idx',
        ),
    ]
