# Generated by Django 5.2.15 on 2026-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_rename_auditoria_entidad_entidad_id_idx_auditoria_r_entidad_0cbcba_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('restaurar', 'Restaurar'), ('publicar', 'Publicar'), ('cerrar', 'Cerrar'), ('archivar', 'Archivar'), ('consultar', 'Consultar'), ('exportar', 'Exportar'), ('iniciar_sesion', 'Iniciar sesion'), ('finalizar_formulario', 'Finalizar formulario'), ('sincronizar', 'Sincronizar'), ('acceso_denegado', 'Acceso denegado')], max_length=30),
        ),
    ]
