# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_alter_registroauditoria_accion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroauditoria',
            options={'ordering': ['-fecha_accion'], 'verbose_name': 'Registro de auditoría', 'verbose_name_plural': 'Registros de auditoria'},
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('restaurar', 'Restaurar'), ('publicar', 'Publicar'), ('cerrar', 'Cerrar'), ('archivar', 'Archivar'), ('consultar', 'Consultar'), ('exportar', 'Exportar'), ('iniciar_sesion', 'Iniciar sesión'), ('finalizar_sesion', 'Finalizar sesión'), ('registrar_usuario', 'Registrar usuario'), ('editar_perfil', 'Editar perfil'), ('cambiar_password', 'Cambiar contraseña'), ('solicitar_restaurar_password', 'Solicitar restaurar contraseña'), ('password_restaurado', 'Contraseña restaurada'), ('contacto_enviado', 'Contacto enviado'), ('copia_respuestas_enviada', 'Copia respuestas enviada'), ('correo_enviado', 'Correo enviado'), ('correo_fallido', 'Correo fallido'), ('versionar', 'Versionar'), ('finalizar_formulario', 'Finalizar formulario'), ('sincronizar', 'Sincronizar'), ('acceso_denegado', 'Acceso denegado'), ('conflicto', 'Conflicto'), ('resolucion_conflicto', 'Resolución de conflicto')], max_length=30),
        ),
    ]
