# Generated by Django 5.2.15 on 2026-06-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInterfaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aplicativo', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(blank=True, max_length=100)),
                ('descripcion_aplicativo', models.TextField(blank=True)),
                ('texto_pie_pagina', models.CharField(blank=True, max_length=255)),
                ('logo_principal', models.ImageField(blank=True, null=True, upload_to='interfaz/logos/')),
                ('logo_secundario', models.ImageField(blank=True, null=True, upload_to='interfaz/logos/')),
                ('logo_institucional', models.ImageField(blank=True, null=True, upload_to='interfaz/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='interfaz/favicon/')),
                ('color_primario', models.CharField(blank=True, max_length=20)),
                ('color_secundario', models.CharField(blank=True, max_length=20)),
                ('color_acento', models.CharField(blank=True, max_length=20)),
                ('esta_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de interfaz',
                'verbose_name_plural': 'Configuraciones de interfaz',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['esta_activa'], name='contenidos__esta_ac_d3b1f1_idx')],
            },
        ),
    ]
