# Generated by Django 5.2.15 on 2026-06-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_auditoria_campos'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='configuracioninterfaz',
            name='contenidos_cfg_esta_elim_idx',
        ),
        migrations.RemoveIndex(
            model_name='configuracioninterfaz',
            name='contenidos_cfg_fecha_cre_idx',
        ),
    ]
