# Generated by Django 5.2.15 on 2026-06-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0003_remove_configuracioninterfaz_contenidos_cfg_esta_elim_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='accion_lengua_senas_habilitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='email_soporte',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='meta_descripcion_seo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='meta_titulo_seo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_autorizacion_datos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_confirmacion_envio_subtitulo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_confirmacion_envio_titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_descripcion_seccion_encuestas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_lengua_senas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_terminos_condiciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_titulo_seccion_encuestas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_verificacion_exitosa_cuerpo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='texto_verificacion_exitosa_titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='url_lengua_senas',
            field=models.URLField(blank=True),
        ),
    ]
