# Generated by Django 5.2.15 on 2026-06-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
        ('contenidos', '0004_configuracioninterfaz_accion_lengua_senas_habilitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='favicon_repositorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_favicon', to='archivos.archivorepositorio'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='logo_institucional_repositorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_logo_institucional', to='archivos.archivorepositorio'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='logo_principal_repositorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_logo_principal', to='archivos.archivorepositorio'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='logo_secundario_repositorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_logo_secundario', to='archivos.archivorepositorio'),
        ),
    ]
