# Generated by Django 5.2.15 on 2026-06-28 21:28

import aplicaciones.auditoria.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
        ('contenidos', '0005_configuracioninterfaz_favicon_repositorio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoInterfaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('texto_alternativo', models.CharField(blank=True, max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='interfaz/logos/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('esta_activo', models.BooleanField(default=True)),
                ('archivo_repositorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logos_interfaz', to='archivos.archivorepositorio')),
                ('configuracion_interfaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='contenidos.configuracioninterfaz')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logo de interfaz',
                'verbose_name_plural': 'Logos de interfaz',
                'ordering': ['configuracion_interfaz', 'orden', 'codigo'],
                'indexes': [models.Index(fields=['configuracion_interfaz'], name='contenidos__configu_75d677_idx'), models.Index(fields=['codigo'], name='contenidos__codigo_01aa92_idx'), models.Index(fields=['esta_activo'], name='contenidos__esta_ac_45d8fe_idx'), models.Index(fields=['orden'], name='contenidos__orden_3ec645_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('esta_eliminado', False)), fields=('configuracion_interfaz', 'codigo'), name='uq_logo_interfaz_config_codigo_activo')],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
    ]
