# Generated by Django 5.2.15 on 2026-07-01 05:46

import aplicaciones.auditoria.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0007_migrar_logos_legacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFlujoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modal_salir_titulo', models.CharField(blank=True, max_length=255)),
                ('modal_salir_p1', models.TextField(blank=True)),
                ('modal_salir_p2', models.TextField(blank=True)),
                ('modal_salir_btn_volver', models.CharField(blank=True, max_length=255)),
                ('modal_salir_btn_salir', models.CharField(blank=True, max_length=255)),
                ('modal_salir_link_sesion', models.CharField(blank=True, max_length=255)),
                ('modal_sesion_titulo', models.CharField(blank=True, max_length=255)),
                ('modal_sesion_parrafo', models.TextField(blank=True)),
                ('modal_sesion_btn_login', models.CharField(blank=True, max_length=255)),
                ('modal_sesion_btn_registro', models.CharField(blank=True, max_length=255)),
                ('modal_sesion_link_cancelar', models.CharField(blank=True, max_length=255)),
                ('modal_guardado_titulo', models.CharField(blank=True, max_length=255)),
                ('modal_guardado_parrafo', models.TextField(blank=True)),
                ('modal_guardado_btn_seguir', models.CharField(blank=True, max_length=255)),
                ('modal_guardado_btn_otras', models.CharField(blank=True, max_length=255)),
                ('terminos_titulo', models.CharField(blank=True, max_length=500)),
                ('terminos_contenido', models.TextField(blank=True)),
                ('terminos_p1', models.TextField(blank=True)),
                ('terminos_p2', models.TextField(blank=True)),
                ('terminos_p3', models.TextField(blank=True)),
                ('terminos_url_ley', models.URLField(blank=True)),
                ('terminos_url_politica_datos', models.URLField(blank=True)),
                ('terminos_email_soporte', models.EmailField(blank=True, max_length=254)),
                ('esta_activa', models.BooleanField(default=True)),
                ('configuracion_interfaz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_flujo', to='contenidos.configuracioninterfaz')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion de flujo de formulario',
                'verbose_name_plural': 'Configuraciones de flujo de formulario',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['esta_activa'], name='contenidos__esta_ac_71bb10_idx'), models.Index(fields=['uuid'], name='contenidos__uuid_7eb94f_idx')],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
    ]
