# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0011_corregir_texto_boton_terminos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionflujoformulario',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Configuración de flujo de formulario', 'verbose_name_plural': 'Configuraciones de flujo de formulario'},
        ),
        migrations.AlterModelOptions(
            name='configuracioninterfaz',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Configuración de interfaz', 'verbose_name_plural': 'Configuraciones de interfaz'},
        ),
    ]
