# Generated by Django 5.2.15 on 2026-07-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0017_configuracionflujoformulario_imagen_envio_exito'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='accesibilidad_comandos_voz_habilitada',
            field=models.BooleanField(default=False, help_text='Habilita la navegacion mediante comandos de voz.'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='accesibilidad_fuente_dislexia_habilitada',
            field=models.BooleanField(default=False, help_text='Habilita la opcion de fuente adaptada para dislexia.'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='accesibilidad_lectura_voz_habilitada',
            field=models.BooleanField(default=True, help_text='Habilita la lectura por voz (texto a voz) de los contenidos.'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='accesibilidad_tema_por_defecto',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('alto_contraste', 'Alto contraste')], default='claro', help_text='Tema de contraste inicial que aplica el frontend.', max_length=20),
        ),
    ]
