# Generated by Django 5.2.15 on 2026-07-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0018_accesibilidad_configuracion_interfaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='centro_relevo_habilitado',
            field=models.BooleanField(default=False, help_text='Muestra en la barra de accesibilidad un enlace al Centro de Relevo.'),
        ),
        migrations.AddField(
            model_name='configuracioninterfaz',
            name='url_centro_relevo',
            field=models.URLField(blank=True, help_text='URL del servicio Centro de Relevo para comunicacion asistida por interprete.'),
        ),
    ]
