# Generated by Django 5.2.15 on 2026-06-28 17:45

import aplicaciones.auditoria.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_catalogo', models.CharField(max_length=100)),
                ('esta_activo', models.BooleanField(default=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
                'ordering': ['orden', 'nombre'],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.CharField(blank=True, max_length=255)),
                ('codigo_externo', models.CharField(blank=True, max_length=100)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('esta_activo', models.BooleanField(default=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogos.catalogo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_hijos', to='catalogos.itemcatalogo')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de catalogo',
                'verbose_name_plural': 'Items de catalogo',
                'ordering': ['catalogo', 'orden', 'nombre'],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='catalogo',
            index=models.Index(fields=['esta_activo'], name='catalogos_c_esta_ac_b02893_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogo',
            index=models.Index(fields=['tipo_catalogo'], name='catalogos_c_tipo_ca_479cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogo',
            index=models.Index(fields=['orden'], name='catalogos_c_orden_20aa36_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['catalogo'], name='catalogos_i_catalog_3a13dd_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['codigo'], name='catalogos_i_codigo_b916d9_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['esta_activo'], name='catalogos_i_esta_ac_0c388b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['item_padre'], name='catalogos_i_item_pa_508a19_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['codigo_externo'], name='catalogos_i_codigo__fc9b47_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['orden'], name='catalogos_i_orden_81fcbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcatalogo',
            constraint=models.UniqueConstraint(condition=models.Q(('esta_eliminado', False)), fields=('catalogo', 'codigo'), name='uq_item_catalogo_catalogo_codigo_activo'),
        ),
    ]
