# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Catálogo', 'verbose_name_plural': 'Catalogos'},
        ),
        migrations.AlterModelOptions(
            name='itemcatalogo',
            options={'ordering': ['catalogo', 'orden', 'nombre'], 'verbose_name': 'Ítem de catálogo', 'verbose_name_plural': 'Items de catalogo'},
        ),
    ]
