# Generated by Django 5.2.15 on 2026-07-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permiso del sistema',
                'verbose_name_plural': 'Permisos del sistema',
                'permissions': [('puede_gestionar_formularios', 'Puede gestionar formularios'), ('puede_publicar_formularios', 'Puede publicar formularios'), ('puede_versionar_formularios', 'Puede versionar formularios'), ('puede_consultar_formularios_admin', 'Puede consultar formularios en administracion'), ('puede_exportar_respuestas', 'Puede exportar respuestas'), ('puede_gestionar_usuarios', 'Puede gestionar usuarios')],
            },
        ),
    ]
