# Generated by Django 5.2.15 on 2026-06-28 19:16

import aplicaciones.auditoria.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('correo', 'Correo'), ('sms', 'SMS'), ('push', 'Push'), ('interna', 'Interna'), ('webhook', 'Webhook')], max_length=20)),
                ('asunto', models.CharField(blank=True, max_length=300)),
                ('contenido_html', models.TextField(blank=True)),
                ('contenido_texto', models.TextField(blank=True)),
                ('usa_variables', models.BooleanField(default=True)),
                ('variables_disponibles', models.JSONField(blank=True, default=list, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de notificacion',
                'verbose_name_plural': 'Plantillas de notificacion',
                'ordering': ['codigo'],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('canal', models.CharField(choices=[('correo', 'Correo'), ('sms', 'SMS'), ('push', 'Push'), ('interna', 'Interna'), ('webhook', 'Webhook')], max_length=20)),
                ('destinatario', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('asunto_generado', models.CharField(blank=True, max_length=300)),
                ('contenido_generado', models.TextField(blank=True)),
                ('variables_utilizadas', models.JSONField(blank=True, default=dict, null=True)),
                ('respuesta_proveedor', models.JSONField(blank=True, default=dict, null=True)),
                ('numero_intentos', models.PositiveIntegerField(default=0)),
                ('error_envio', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='notificaciones.plantillanotificacion')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='plantillanotificacion',
            index=models.Index(fields=['codigo'], name='notificacio_codigo_666907_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillanotificacion',
            index=models.Index(fields=['tipo'], name='notificacio_tipo_5f57d2_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillanotificacion',
            index=models.Index(fields=['esta_activa'], name='notificacio_esta_ac_cad121_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['uuid'], name='notificacio_uuid_debbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['canal'], name='notificacio_canal_028c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estado'], name='notificacio_estado_52a925_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario'], name='notificacio_destina_0c5a13_idx'),
        ),
    ]
