# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion_contenido_texto_html_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillanotificacion',
            options={'ordering': ['codigo'], 'verbose_name': 'Plantilla de notificación', 'verbose_name_plural': 'Plantillas de notificación'},
        ),
    ]
