# Generated by Django 5.2.15 on 2026-06-28 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('tooltip', models.TextField(blank=True)),
                ('tipo_pregunta', models.CharField(choices=[('texto_corto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Numero'), ('fecha', 'Fecha'), ('hora', 'Hora'), ('fecha_hora', 'Fecha y hora'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('select_multiple', 'Select multiple'), ('autocomplete', 'Autocomplete'), ('likert', 'Likert'), ('matriz', 'Matriz'), ('archivo', 'Archivo'), ('firma', 'Firma'), ('geolocalizacion', 'Geolocalizacion'), ('audio', 'Audio'), ('video', 'Video')], max_length=30)),
                ('es_obligatoria', models.BooleanField(default=False)),
                ('es_pregunta_filtro', models.BooleanField(default=False)),
                ('permite_otro', models.BooleanField(default=False)),
                ('permite_observacion', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField()),
                ('longitud_minima', models.PositiveIntegerField(blank=True, null=True)),
                ('longitud_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('expresion_regular', models.CharField(blank=True, max_length=500)),
                ('mensaje_error', models.TextField(blank=True)),
                ('esta_activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoGeografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pais', 'Pais'), ('departamento', 'Departamento'), ('municipio', 'Municipio')], max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_padre', models.CharField(blank=True, max_length=50)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catalogo geografico',
                'verbose_name_plural': 'Catalogos geograficos',
                'ordering': ['tipo', 'nombre'],
                'indexes': [models.Index(fields=['esta_activo'], name='formularios_esta_ac_c1b79d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'codigo'), name='uq_catalogo_geografico_tipo_codigo')],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('introduccion', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('tipo_formulario', models.CharField(choices=[('encuesta', 'Encuesta'), ('caracterizacion', 'Caracterizacion'), ('inscripcion', 'Inscripcion'), ('registro', 'Registro'), ('censo', 'Censo'), ('evaluacion', 'Evaluacion')], max_length=30)),
                ('tiempo_estimado_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado'), ('inactivo', 'Inactivo')], default='borrador', max_length=20)),
                ('version_actual', models.PositiveIntegerField(default=1)),
                ('permite_anonimo', models.BooleanField(default=True)),
                ('permite_registro_final', models.BooleanField(default=True)),
                ('permite_multiples_respuestas', models.BooleanField(default=False)),
                ('permite_offline', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormularioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado'), ('inactivo', 'Inactivo')], default='borrador', max_length=20)),
                ('descripcion_cambio', models.TextField(blank=True)),
                ('es_publicada', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='formularios.formulario')),
            ],
            options={
                'verbose_name': 'Version de formulario',
                'verbose_name_plural': 'Versiones de formulario',
                'ordering': ['formulario', 'numero_version'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=500)),
                ('valor', models.CharField(max_length=255)),
                ('tooltip', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField()),
                ('es_excluyente', models.BooleanField(default=False)),
                ('activa_otro', models.BooleanField(default=False)),
                ('esta_activa', models.BooleanField(default=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='formularios.pregunta')),
            ],
            options={
                'verbose_name': 'Opcion de respuesta',
                'verbose_name_plural': 'Opciones de respuesta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaMatrizColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=500)),
                ('valor', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('esta_activa', models.BooleanField(default=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas_matriz', to='formularios.pregunta')),
            ],
            options={
                'verbose_name': 'Columna de matriz',
                'verbose_name_plural': 'Columnas de matriz',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaMatrizFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=500)),
                ('orden', models.PositiveIntegerField()),
                ('esta_activa', models.BooleanField(default=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_matriz', to='formularios.pregunta')),
            ],
            options={
                'verbose_name': 'Fila de matriz',
                'verbose_name_plural': 'Filas de matriz',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SeccionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('texto_ayuda', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField()),
                ('es_visible', models.BooleanField(default=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('formulario_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='formularios.formularioversion')),
            ],
            options={
                'verbose_name': 'Seccion de formulario',
                'verbose_name_plural': 'Secciones de formulario',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ReglaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals'), ('contains', 'Contains'), ('gt', 'Greater than'), ('lt', 'Less than'), ('in', 'In')], max_length=20)),
                ('valor_esperado', models.JSONField()),
                ('accion', models.CharField(choices=[('mostrar', 'Mostrar'), ('ocultar', 'Ocultar'), ('habilitar', 'Habilitar'), ('deshabilitar', 'Deshabilitar'), ('hacer_obligatoria', 'Hacer obligatoria'), ('hacer_opcional', 'Hacer opcional'), ('saltar_a_pregunta', 'Saltar a pregunta'), ('saltar_a_seccion', 'Saltar a seccion'), ('finalizar_formulario', 'Finalizar formulario'), ('no_aplica_formulario', 'No aplica formulario')], max_length=30)),
                ('mensaje', models.TextField(blank=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('pregunta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_destino', to='formularios.pregunta')),
                ('pregunta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_origen', to='formularios.pregunta')),
                ('seccion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_destino', to='formularios.seccionformulario')),
            ],
            options={
                'verbose_name': 'Regla de pregunta',
                'verbose_name_plural': 'Reglas de pregunta',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='formularios.seccionformulario'),
        ),
        migrations.CreateModel(
            name='TextoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('introduccion', 'Introduccion'), ('definicion', 'Definicion'), ('consentimiento', 'Consentimiento'), ('terminos', 'Terminos'), ('agradecimiento', 'Agradecimiento'), ('ayuda', 'Ayuda'), ('cierre', 'Cierre')], max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('esta_activo', models.BooleanField(default=True)),
                ('formulario_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='formularios.formularioversion')),
            ],
            options={
                'verbose_name': 'Texto de formulario',
                'verbose_name_plural': 'Textos de formulario',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['estado'], name='formularios_estado_683d50_idx'),
        ),
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['codigo'], name='formularios_codigo_d308fc_idx'),
        ),
        migrations.AddIndex(
            model_name='formulario',
            index=models.Index(fields=['tipo_formulario'], name='formularios_tipo_fo_61e459_idx'),
        ),
        migrations.AddIndex(
            model_name='formularioversion',
            index=models.Index(fields=['estado'], name='formularios_estado_702b99_idx'),
        ),
        migrations.AddConstraint(
            model_name='formularioversion',
            constraint=models.UniqueConstraint(fields=('formulario', 'numero_version'), name='uq_formulario_version_numero'),
        ),
        migrations.AddIndex(
            model_name='opcionrespuesta',
            index=models.Index(fields=['orden'], name='formularios_orden_70ecfd_idx'),
        ),
        migrations.AddIndex(
            model_name='opcionrespuesta',
            index=models.Index(fields=['esta_activa'], name='formularios_esta_ac_f6d5f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='opcionrespuesta',
            constraint=models.UniqueConstraint(fields=('pregunta', 'codigo'), name='uq_opcion_respuesta_pregunta_codigo'),
        ),
        migrations.AddIndex(
            model_name='preguntamatrizcolumna',
            index=models.Index(fields=['orden'], name='formularios_orden_a53ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='preguntamatrizcolumna',
            index=models.Index(fields=['esta_activa'], name='formularios_esta_ac_e3853c_idx'),
        ),
        migrations.AddConstraint(
            model_name='preguntamatrizcolumna',
            constraint=models.UniqueConstraint(fields=('pregunta', 'codigo'), name='uq_matriz_columna_pregunta_codigo'),
        ),
        migrations.AddIndex(
            model_name='preguntamatrizfila',
            index=models.Index(fields=['orden'], name='formularios_orden_18e894_idx'),
        ),
        migrations.AddIndex(
            model_name='preguntamatrizfila',
            index=models.Index(fields=['esta_activa'], name='formularios_esta_ac_8c9cd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='preguntamatrizfila',
            constraint=models.UniqueConstraint(fields=('pregunta', 'codigo'), name='uq_matriz_fila_pregunta_codigo'),
        ),
        migrations.AddIndex(
            model_name='seccionformulario',
            index=models.Index(fields=['orden'], name='formularios_orden_0fa93d_idx'),
        ),
        migrations.AddIndex(
            model_name='seccionformulario',
            index=models.Index(fields=['esta_activo'], name='formularios_esta_ac_a4e2fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='seccionformulario',
            constraint=models.UniqueConstraint(fields=('formulario_version', 'codigo'), name='uq_seccion_formulario_version_codigo'),
        ),
        migrations.AddIndex(
            model_name='reglapregunta',
            index=models.Index(fields=['esta_activa'], name='formularios_esta_ac_95316f_idx'),
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['tipo_pregunta'], name='formularios_tipo_pr_dc8b82_idx'),
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['esta_activa'], name='formularios_esta_ac_c882f2_idx'),
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['orden'], name='formularios_orden_19e4fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='pregunta',
            constraint=models.UniqueConstraint(fields=('seccion', 'codigo'), name='uq_pregunta_seccion_codigo'),
        ),
        migrations.AddIndex(
            model_name='textoformulario',
            index=models.Index(fields=['orden'], name='formularios_orden_acb4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='textoformulario',
            index=models.Index(fields=['esta_activo'], name='formularios_esta_ac_574bd0_idx'),
        ),
    ]
