# Generated by Django 5.2.15 on 2026-06-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('formularios', '0003_remove_catalogogeografico_form_catgeo_esta_elim_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='campo_codigo_padre_catalogo',
            field=models.CharField(blank=True, default='codigo', max_length=100),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='catalogo_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='catalogos.catalogo'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='limite_items_catalogo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='permite_busqueda_catalogo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='pregunta_padre_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_dependientes_catalogo', to='formularios.pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='usa_catalogo',
            field=models.BooleanField(default=False),
        ),
    ]
