# Generated by Django 5.2.15 on 2026-06-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_pregunta_campo_codigo_padre_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='formularios/portadas/'),
        ),
        migrations.AlterField(
            model_name='textoformulario',
            name='tipo',
            field=models.CharField(choices=[('introduccion', 'Introduccion'), ('definicion', 'Definicion'), ('consentimiento', 'Consentimiento'), ('terminos', 'Terminos'), ('agradecimiento', 'Agradecimiento'), ('ayuda', 'Ayuda'), ('cierre', 'Cierre'), ('consentimiento_datos', 'Consentimiento de datos'), ('confirmacion_envio', 'Confirmacion de envio'), ('verificacion_exitosa', 'Verificacion exitosa'), ('autorizacion_datos', 'Autorizacion de datos'), ('resumen_respuestas', 'Resumen de respuestas'), ('registro_opcional', 'Registro opcional'), ('envio_correo', 'Envio de correo'), ('contacto', 'Contacto'), ('ayuda_accesibilidad', 'Ayuda de accesibilidad')], max_length=30),
        ),
    ]
