# Generated by Django 5.2.15 on 2026-06-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
        ('formularios', '0005_formulario_imagen_portada_alter_textoformulario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='imagen_portada_repositorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_portada', to='archivos.archivorepositorio'),
        ),
    ]
