# Generated by Django 5.2.15 on 2026-07-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_formulario_orden'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formulario',
            new_name='formularios_orden_6d3759_idx',
            old_name='formularios_orden_4b8f2a_idx',
        ),
    ]
