# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0010_pregunta_flujo_condicional_ubicacion_geografica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogogeografico',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Catálogo geográfico', 'verbose_name_plural': 'Catálogos geográficos'},
        ),
        migrations.AlterModelOptions(
            name='formularioversion',
            options={'ordering': ['formulario', 'numero_version'], 'verbose_name': 'Versión de formulario', 'verbose_name_plural': 'Versiones de formulario'},
        ),
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'ordering': ['orden'], 'verbose_name': 'Opción de respuesta', 'verbose_name_plural': 'Opciones de respuesta'},
        ),
        migrations.AlterModelOptions(
            name='seccionformulario',
            options={'ordering': ['orden'], 'verbose_name': 'Sección de formulario', 'verbose_name_plural': 'Secciones de formulario'},
        ),
        migrations.AlterField(
            model_name='catalogogeografico',
            name='tipo',
            field=models.CharField(choices=[('pais', 'País'), ('departamento', 'Departamento'), ('municipio', 'Municipio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tipo_formulario',
            field=models.CharField(choices=[('encuesta', 'Encuesta'), ('caracterizacion', 'Caracterización'), ('inscripcion', 'Inscripción'), ('registro', 'Registro'), ('censo', 'Censo'), ('evaluacion', 'Evaluación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='codigo_catalogo_departamento',
            field=models.CharField(blank=True, default='', help_text='Código del catálogo de departamentos para ubicación geográfica.', max_length=50),
        ),
        migrations.AlterField(
            model_name='reglapregunta',
            name='accion',
            field=models.CharField(choices=[('mostrar', 'Mostrar'), ('ocultar', 'Ocultar'), ('habilitar', 'Habilitar'), ('deshabilitar', 'Deshabilitar'), ('hacer_obligatoria', 'Hacer obligatoria'), ('hacer_opcional', 'Hacer opcional'), ('saltar_a_pregunta', 'Saltar a pregunta'), ('saltar_a_seccion', 'Saltar a sección'), ('finalizar_formulario', 'Finalizar formulario'), ('no_aplica_formulario', 'No aplica formulario')], max_length=30),
        ),
        migrations.AlterField(
            model_name='textoformulario',
            name='tipo',
            field=models.CharField(choices=[('introduccion', 'Introducción'), ('definicion', 'Definición'), ('consentimiento', 'Consentimiento'), ('terminos', 'Términos'), ('agradecimiento', 'Agradecimiento'), ('ayuda', 'Ayuda'), ('cierre', 'Cierre'), ('consentimiento_datos', 'Consentimiento de datos'), ('confirmacion_envio', 'Confirmación de envío'), ('verificacion_exitosa', 'Verificación exitosa'), ('autorizacion_datos', 'Autorización de datos'), ('resumen_respuestas', 'Resumen de respuestas'), ('registro_opcional', 'Registro opcional'), ('envio_correo', 'Envío de correo'), ('contacto', 'Contacto'), ('ayuda_accesibilidad', 'Ayuda de accesibilidad')], max_length=30),
        ),
    ]
