# Generated by Django 5.2.15 on 2026-07-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0013_sincronizar_validacion_filtros_semilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoformulario',
            name='tipo',
            field=models.CharField(choices=[('introduccion', 'Introducción'), ('definicion', 'Definición'), ('consentimiento', 'Consentimiento'), ('terminos', 'Términos'), ('agradecimiento', 'Agradecimiento'), ('ayuda', 'Ayuda'), ('cierre', 'Cierre'), ('consentimiento_datos', 'Consentimiento de datos'), ('confirmacion_envio', 'Confirmación de envío'), ('verificacion_exitosa', 'Verificación exitosa'), ('autorizacion_datos', 'Autorización de datos'), ('resumen_respuestas', 'Resumen de respuestas'), ('registro_opcional', 'Registro opcional'), ('envio_correo', 'Envío de correo'), ('contacto', 'Contacto'), ('ayuda_accesibilidad', 'Ayuda de accesibilidad'), ('no_cumple_condiciones', 'No cumple condiciones')], max_length=30),
        ),
    ]
