# Generated by Django 5.2.15 on 2026-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0014_alter_textoformulario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='texto_otro_obligatorio',
            field=models.BooleanField(default=False, help_text='Indica si el texto libre asociado a una opcion tipo otro es obligatorio cuando dicha opcion resulta seleccionada.'),
        ),
    ]
