# Generated by Django 5.2.15 on 2026-07-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0019_migrar_catalogo_geografico_a_catalogos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoGeografico',
        ),
    ]
