# Generated by Django 5.2.15 on 2026-06-28 18:02

import aplicaciones.auditoria.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('codigo_iso', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_nativo', models.CharField(max_length=100)),
                ('direccion_texto', models.CharField(choices=[('LTR', 'LTR'), ('RTL', 'RTL')], default='LTR', max_length=3)),
                ('esta_activo', models.BooleanField(default=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('icono_bandera', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['orden', 'nombre'],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TraduccionContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('esta_eliminado', models.BooleanField(default=False)),
                ('entidad', models.CharField(max_length=100)),
                ('entidad_uuid', models.UUIDField()),
                ('campo', models.CharField(max_length=100)),
                ('valor_traducido', models.TextField()),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='internacionalizacion.idioma')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traduccion de contenido',
                'verbose_name_plural': 'Traducciones de contenido',
                'ordering': ['entidad', 'campo'],
            },
            bases=(aplicaciones.auditoria.mixins.AuditoriaMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='idioma',
            index=models.Index(fields=['esta_activo'], name='internacion_esta_ac_19661e_idx'),
        ),
        migrations.AddIndex(
            model_name='idioma',
            index=models.Index(fields=['es_predeterminado'], name='internacion_es_pred_3f308f_idx'),
        ),
        migrations.AddIndex(
            model_name='idioma',
            index=models.Index(fields=['orden'], name='internacion_orden_504431_idx'),
        ),
        migrations.AddIndex(
            model_name='traduccioncontenido',
            index=models.Index(fields=['idioma'], name='internacion_idioma__e34a54_idx'),
        ),
        migrations.AddIndex(
            model_name='traduccioncontenido',
            index=models.Index(fields=['entidad'], name='internacion_entidad_5735bf_idx'),
        ),
        migrations.AddIndex(
            model_name='traduccioncontenido',
            index=models.Index(fields=['entidad_uuid'], name='internacion_entidad_f8d1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='traduccioncontenido',
            index=models.Index(fields=['campo'], name='internacion_campo_1972c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='traduccioncontenido',
            constraint=models.UniqueConstraint(condition=models.Q(('esta_eliminado', False)), fields=('idioma', 'entidad', 'entidad_uuid', 'campo'), name='uq_traduccion_idioma_entidad_campo_activa'),
        ),
    ]
