# Generated by Django 5.2.15 on 2026-06-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacionalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccioncontenido',
            name='archivo_audio',
            field=models.FileField(blank=True, null=True, upload_to='internacionalizacion/audio/'),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='archivo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='internacionalizacion/imagenes/'),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='archivo_lengua_senas',
            field=models.FileField(blank=True, null=True, upload_to='internacionalizacion/lengua_senas/'),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='archivo_video',
            field=models.FileField(blank=True, null=True, upload_to='internacionalizacion/video/'),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='esta_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='lectura_facil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='metadatos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='texto_alternativo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='transcripcion',
            field=models.TextField(blank=True),
        ),
    ]
