# Generated by Django 5.2.15 on 2026-06-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
        ('internacionalizacion', '0002_traduccioncontenido_archivo_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traduccioncontenido',
            name='archivo_audio',
        ),
        migrations.RemoveField(
            model_name='traduccioncontenido',
            name='archivo_imagen',
        ),
        migrations.RemoveField(
            model_name='traduccioncontenido',
            name='archivo_lengua_senas',
        ),
        migrations.RemoveField(
            model_name='traduccioncontenido',
            name='archivo_video',
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='repositorio_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traducciones_audio', to='archivos.archivorepositorio'),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='repositorio_imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traducciones_imagen', to='archivos.archivorepositorio'),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='repositorio_lengua_senas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traducciones_lengua_senas', to='archivos.archivorepositorio'),
        ),
        migrations.AddField(
            model_name='traduccioncontenido',
            name='repositorio_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traducciones_video', to='archivos.archivorepositorio'),
        ),
    ]
