# Generated by Django 5.2.15 on 2026-07-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internacionalizacion', '0003_remove_traduccioncontenido_archivo_audio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traduccioncontenido',
            options={'ordering': ['entidad', 'campo'], 'verbose_name': 'Traducción de contenido', 'verbose_name_plural': 'Traducciones de contenido'},
        ),
    ]
